REV_EXAM_3/Controllers/BasicDemoClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using REV_EXAM_3.Models;

namespace REV_EXAM_3.Controllers
{
    public class BasicDemoClassesController : Controller
    {
        private REV_EXAM_3Context db = new REV_EXAM_3Context();

        // GET: BasicDemoClasses
        public ActionResult Index()
        {
            return View(db.BasicDemoClasses.ToList());
        }

        // GET: BasicDemoClasses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BasicDemoClass basicDemoClass = db.BasicDemoClasses.Find(id);
            if (basicDemoClass == null)
            {
                return HttpNotFound();
            }
            return View(basicDemoClass);
        }

        // GET: BasicDemoClasses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BasicDemoClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "myPk,name1,randomeDate")] BasicDemoClass basicDemoClass)
        {
            if (ModelState.IsValid)
            {
                db.BasicDemoClasses.Add(basicDemoClass);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(basicDemoClass);
        }

        // GET: BasicDemoClasses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BasicDemoClass basicDemoClass = db.BasicDemoClasses.Find(id);
            if (basicDemoClass == null)
            {
                return HttpNotFound();
            }
            return View(basicDemoClass);
        }

        // POST: BasicDemoClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "myPk,name1,randomeDate")] BasicDemoClass basicDemoClass)
        {
            if (ModelState.IsValid)
            {
                db.Entry(basicDemoClass).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(basicDemoClass);
        }

        // GET: BasicDemoClasses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BasicDemoClass basicDemoClass = db.BasicDemoClasses.Find(id);
            if (basicDemoClass == null)
            {
                return HttpNotFound();
            }
            return View(basicDemoClass);
        }

        // POST: BasicDemoClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BasicDemoClass basicDemoClass = db.BasicDemoClasses.Find(id);
            db.BasicDemoClasses.Remove(basicDemoClass);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // MY MODIFICATIONS

        public ActionResult BOG_Index()
        {
            //This is a LINQ statment, it similar to a sql stament but for this project
            // For this page, I select only records  written by asdf but them into a list
            var linqDemo = (from e in db.BasicDemoClasses
                            where e.name1.Equals("asdf")
                            select e).ToList();
            //  can be replaced by anything
            // db is the entity created to access DB/Context (See line 15), 
            //basically the one created when first scafolded
            // The rest is pretty self explanatory

            //Here I am returning the list to my view
            return View(linqDemo);
        }



    }
}

REV_EXAM_3/Controllers/MainController.cs
using REV_EXAM_3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Angela.Core;
using REV_EXAM_3;
using REV_EXAM_3.ViewModels;

namespace REV_EXAM_3.Controllers
{
    public class MainController : Controller
    {
        // import the models in order to access the Context/DB
       private REV_EXAM_3Context db = new REV_EXAM_3Context();

        // GET: Main
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SpecificTemplates()
        {
            // Basically, when I will access the view, I will retrieve
            // all BasicDemoClasse instances in the DB
            return View(db.BasicDemoClasses.ToList());
        }


        public static ICollection<DBFirstDemo> myListOfItems = new List<DBFirstDemo>();
        public ActionResult ANGELA()
        {
            // What is Angela Smith? Angela Smith is an extension that insert dumb data in the DB
            // In order to make it work, follow thos exact same steps, don't do anything else
            /*
             * 1)  In nugget console type: Install-Package AngelaSmith –Version 1.0.1
             *          !!!!!!!!! don't install the newest one else it won't work !!!!!!!!!
             * 2) import Angela.Core: using Angela.Core;
             * 3) create an ICollection of the model you want (see above this methode)
             *      !!!!! To make sure it works, you have to make sure that your Table,!!!!
             *      !!!!! if you have a date field, it has to be of type: dateTime2 !!!!
             *      !!!!! Else, it won't work if you want to generate a date !!!!!!
             *      !!!2! Also, Do not allow nullable in the model !!!!
             */
            
           //How Angela works. 
           List<DBFirstDemo> new2Rec = Angie.Configure<DBFirstDemo>() //This line is just how it is
                           .Fill(x => x.value1).AsFirstName() // I add a value to my value1 in my model that is filled with what Angela considers a first name
                           .Fill(y => y.value2).WithinRange((int)1, (int)500) // I set an integer in between 1 and 500 for my value2 in my model
                           .Fill(z => z.value4).AsPastDate() // I set a date for my value4 in the model
                           .MakeList<DBFirstDemo>(2); // I tell him to make of them everytime I call this methode and to add them in the List

           //So Right now I just created a list with 2 new records

           // Now lets say we want to save them in the DB and save them in the myListOfItems
           foreach(DBFirstDemo x in new2Rec)
           {
               // For some reason, you have to create a new object that will be added
               DBFirstDemo newRecord = new DBFirstDemo {
                      value1 = x.value1,
                      value2 = x.value2,
                      value4 = x.value4
               };

                // To be able to acces them, if code first, you need to scafold them
               db.DBFirstDemoes.Add(newRecord); //Adds the object to the table
               db.SaveChanges(); // Save the table


                
                myListOfItems.Add(newRecord); // Adds the record to the List

           }
           
            // Here we are only returning the list
            //return View(myListOfItems);


            //Or we could have had return the list from DB (uncomment and comment line 77)
            return View(db.DBFirstDemoes.ToList());

        }

        //creating a list of records to display, dont forget to import ViewModels
        public List<Combo> someFusion = new List<Combo>();
        public ActionResult ComboOf2Models()
        {
            // LINQ to select all records in BasicDemoClass Table
            // then puts them in a table
            var allBasicDemoClass = (from x in db.BasicDemoClasses
                                     select x).ToList();

            //LINQ select all records in DBFirstDemo Table
            var allDBFirstDemo = (from x in db.DBFirstDemoes
                                  select x).ToList();


            // initilizating an enumerator in order to keep track of the posisiton
            // of the record in BasicDemoClass (All this because I have less record in that table than in DBFirstDemo)
            int enumarator = 0;
            foreach(var rec in allBasicDemoClass)
            {
                enumarator++;
                Combo fusion = new Combo {
                    // set xyz from the Combo View Model to the value of the DBFirstDemo
                    // value1 that is at the enumerator position
                       xyz = allDBFirstDemo.ElementAt(enumarator).value1,
                       abc = allDBFirstDemo.ElementAt(enumarator).value2,

                    // set value of name1 in Combo View Model as the one in the allBasicDemoClass 
                       name1 = rec.name1,
                       randomeDate = rec.randomeDate
                };

                // Add to the list
                someFusion.Add(fusion);
            }
            // Yes my example makes no sense, but its just to show you hpw you can combine
            // the values of multiple models in one, that is called a View Model
            
            // Return the list
            return View(someFusion);
        }
    }
}

REV_EXAM_3/Views/Main/ANGELA.cshtml
@model IEnumerable<REV_EXAM_3.Models.DBFirstDemo>

@{
    ViewBag.Title = "ANGELA";
}

<h2>ANGELA</h2>

 @*This page page only shows the results of how AngelSmith works
All the explanation is in the controller*@


<!-- Manual foreach in for the list, also understand that we could have done 
    a display template for this one too-->
@foreach(var x in Model)
{
<div style="border:2px solid green;">
    <p>@x.Id</p>
    <p>@x.value1</p>
    <p>@x.value2</p>
    <p>@x.value4</p>
</div>
    <br />
}

REV_EXAM_3/Views/Main/ComboOf2Models.cshtml
@model IEnumerable<REV_EXAM_3.ViewModels.Combo>

@{
    ViewBag.Title = "ComboOf2Models";
}

<h2>ComboOf2Models</h2>

@*To see how to do a template for a model, see SpecificTemple in Main folder

This page is for a view Model see the ViewModel Combo and i the main controller at 
the methode ComboOf2Models for explanation*@


@Html.DisplayForModel(Model)

REV_EXAM_3/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>In this review we will review the following points</p>
<p>Look in the code for the explanation, this is just a display example</p>
<p>Yes for once I documented my shits and fairly enough</p>
<ul>
    <li>@Html.ActionLink("Scaffolding steps", "BOG_Index", "BasicDemoClasses")</li>
    <li>@Html.ActionLink("LINQ", "BOG_Index", "BasicDemoClasses")</li>
    <li>@Html.ActionLink("View Models", "ComboOf2Models", "Main")</li>
    <li>@Html.ActionLink("Custom Templates", "SpecificTemplates", "Main")</li>
    <li>@Html.ActionLink("Angela Smith", "ANGELA", "Main")</li>
</ul>

<p>Note there was no DB first, since I started the project with code first and you cannot,
    Technically, mix them (It was hell)</p>
<p>ENJOY!!!!</p>

REV_EXAM_3/Views/Main/SpecificTemplates.cshtml
@model IEnumerable<REV_EXAM_3.Models.BasicDemoClass>


@{
    ViewBag.Title = "SpecificTemplates";
}

<h2>Specific Templates for a specific model</h2>

@*In this section I will explain hw to set specific templates for specific
    models:

    1) In your Shared folder, create a folder called exactly like this: DisplayTemplates
    2) Then in the DisplayTemplates folder, create a new normal View Called Exactly as one of the model
            In my case I will create one called BasicDemoClass, in order to fit with my BasicDemoClass.cs
    ***** When done, proceed to step 3 ********
3) To display a list of item, again, you have to make it IEnumerable, so again,
        go to line 1 and add it, once more IEnumerable, because in the controller, we sed a list
        of them
4) The line on line 25 and it will automatically display with the template created in you DisplayTemplates folder


*@

@Html.DisplayForModel(Model);
<!--
    This line automatically applies for every element in the list so no foreach loop needed
-->